require("codevogel.autostart")
require("codevogel.binds")
require("codevogel.look")
require("codevogel.windowrules")
require("codevogel.monitors") -- This module is generated by nix
require("codevogel.remap")
