{ ... }:

{
  imports = [
    ./system/theme/stylix.nix
    ./apps/browser/ungoogled-chromium/webapps/chatgpt.nix
    ./apps/browser/ungoogled-chromium/webapps/claude.nix
    ./apps/browser/ungoogled-chromium/webapps/discord.nix
    ./apps/browser/ungoogled-chromium/webapps/github.nix
    ./apps/browser/ungoogled-chromium/webapps/home-manager-search.nix
    ./apps/browser/ungoogled-chromium/webapps/nixos-search.nix
    ./apps/browser/ungoogled-chromium/webapps/whatsapp-web.nix
    ./apps/browser/ungoogled-chromium/mkWebApp.nix
    ./apps/browser/ungoogled-chromium/ungoogled-chromium.nix
    ./system/audio.nix
    ./apps/dev/bashly.nix
    ./apps/dev/blender.nix
    ./system/bluetooth.nix
    ./system/boot.nix
    ./apps/dev/dotnet.nix
    ./apps/dev/formatters-and-linters.nix
    ./apps/dev/godot.nix
    ./system/greeter.nix
    ./system/home-manager.nix
    ./system/hyprland/hyprland.nix
    ./system/keymap.nix
    ./apps/dev/lazygit.nix
    ./system/locale.nix
    ./apps/file-explorer/nautilus.nix
    ./system/neovim.nix
    ./system/networking.nix
    ./apps/dev/nodejs.nix
    ./system/nvidia.nix
    ./apps/media/obs-studio.nix
    ./apps/obsidian.nix
    ./system/hyprland/peck.nix
    ./apps/media/playerctl.nix
    ./apps/qbittorrent.nix
    ./system/sops.nix
    ./apps/media/spotify.nix
    ./apps/steam.nix
    ./apps/dev/unityhub.nix
    ./system/users.nix
    ./apps/dev/vhs.nix
    ./apps/media/vlc.nix
    ./apps/dev/vscode.nix
  ];
}
