commands:
  - alias: clone
    command: git clone git@github.com:codevogel/$1.git
  - alias: clonex
    command: git clone git@github.com:$1/$2.git
  - alias: dev
    command: ~/.config/tmux/startup/dev-default.sh
  - alias: dev-sv
    command: ~/.config/tmux/startup/dev-svelte.sh
  - alias: rebuild
    command: if [[ -z "$1" ]]; then sudo nixos-rebuild switch --flake ~/nixos#home-nest; else sudo nixos-rebuild switch --flake ~/nixos#"${1}"; fi
